### ISSUE TITLE
Add support for WASM target

### ISSUE THREAD

**Issue by c0dearm** [c0dearm/sharks#7]
Would love seeing this crate working on the web!

**Comment by zer0x64** [comment]
I've done this a bunch of time, so I can do this without any problem. Leave this to me, this should be done within the next 24 hours!

**Comment by c0dearm** [comment]
Holy cow, you are great!

**Comment by zer0x64** [comment]
Opened draft opened here:
https://github.com/c0dearm/sharks/pull/10

I'll try to work a bit to get the shares as an opaque pointer, I believe it would be cleaner.

**Comment by c0dearm** [comment]
Working on this in another repo: https://github.com/c0dearm/sharks-wasm
